# GitHub Action: Sync Firestore Database
#
# This workflow uses service account key authentication to sync database to Firestore

name: Sync Firestore Database

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'Database/**.json'
      - 'database/**.json'

jobs:
  firestore-sync:
    name: Upload Database to Firestore
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase Admin
        run: npm install firebase-admin

      - name: Sync Database to Firestore
        run: node Scripts/sync-firestore.js
