# GitHub Action: Sync Firestore
#
# This workflow automatically updates the Firestore database whenever changes
# are pushed to the JSON files in the 'Database/' directory on the main/master branch.

name: Sync Firestore Data

on:
  push:
    branches:
      - main
      - master # Handle both main and master branches
    paths:
      - 'Database/**.json' # Only run when JSON files in this directory change
      - 'database/**.json' # Handle both uppercase and lowercase

jobs:
  sync-to-firestore:
    name: Sync Data to Live Firestore
    runs-on: ubuntu-latest

    # Add permissions to allow authentication with Google Cloud
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          # Required GitHub Secrets (set these in your repository settings):
          # 1. GCP_WORKLOAD_IDENTITY_PROVIDER - Your workload identity provider
          # 2. GCP_SERVICE_ACCOUNT_EMAIL - Your service account email
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install firebase-admin

      - name: Run Firestore Sync Script
        run: node Scripts/sync-firestore.js
        env:
          # Ensure the script has access to the authentication context
          GOOGLE_APPLICATION_CREDENTIALS: ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}
