# Firestore Database Sync - Fresh Start
# This is a completely new workflow with a unique name

name: Firestore Database Upload

on:
  push:
    branches: [main, master]
    paths: ['Database/**.json', 'database/**.json']
  workflow_dispatch: # Allow manual triggering

jobs:
  upload-database:
    name: Upload to Firestore
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Google Cloud Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Enable Required APIs and Initialize Firestore
        run: |
          echo "Enabling required Google Cloud APIs..."
          gcloud services enable firestore.googleapis.com
          gcloud services enable cloudbuild.googleapis.com
          
          echo "Checking if Firestore database exists..."
          if ! gcloud firestore databases list --format="value(name)" | grep -q "(default)"; then
            echo "Creating Firestore database in Native mode..."
            gcloud firestore databases create --region=us-central1 --type=firestore-native
          else
            echo "Firestore database already exists."
          fi
          
      - name: Install Firebase Admin SDK
        run: npm install firebase-admin
        
      - name: Set Google Cloud Project
        run: |
          echo "GOOGLE_CLOUD_PROJECT=sunny-furnace-461114-s9" >> $GITHUB_ENV
          echo "FIRESTORE_EMULATOR_HOST=" >> $GITHUB_ENV
          
      - name: Debug Environment and Permissions
        run: |
          echo "=== DEBUGGING FIRESTORE ACCESS ==="
          echo "Project ID: $GOOGLE_CLOUD_PROJECT"
          echo "Current user:"
          gcloud auth list
          echo ""
          echo "Project configuration:"
          gcloud config list
          echo ""
          echo "Available services:"
          gcloud services list --enabled --filter="name:firestore.googleapis.com"
          echo ""
          echo "Firestore databases:"
          gcloud firestore databases list
          echo ""
          echo "Service account permissions:"
          gcloud projects get-iam-policy sunny-furnace-461114-s9 --flatten="bindings[].members" --format="table(bindings.role)" --filter="bindings.members:stackfast-github-actions@sunny-furnace-461114-s9.iam.gserviceaccount.com"
          echo ""
          echo "Testing Firestore access with gcloud..."
          gcloud firestore collections list || echo "Failed to list collections - likely permission issue"
          
      - name: Execute Firestore Sync
        run: node Scripts/sync-firestore.js
